**IMPORT DATA**

In [8]:
import pandas as pd 
BoardWay=pd.read_csv(r"C:\Users\Personal Camputer\OneDrive\Desktop\data\starbucks_ny_broadway.csv")
Reserve=pd.read_csv(r"C:\Users\Personal Camputer\OneDrive\Desktop\data\starbucks_ny_reserve_roastery.CSV")

In [16]:
BoardWay.head()

,publishedDate,title,text,rating
0,2024-01-07,Rude people with elder man,"Really rude people on the counter, they bully ...",1
1,2023-12-06,No te permiten entrar en el baño siendo cliente,"Una porquería de servicio , los camareros muy ...",1
2,2023-11-17,Pausa caffè,"Per me che sono un amante dell’espresso, il ca...",3
3,2023-10-06,cappuccino da passeggio,non potevo non provare anche lo Starbucks a Ne...,3
4,2023-09-04,Meglio il Chai del Matcha,In questa vacanza ho evitato questa catena (qu...,3

In [17]:
BoardWay.describe()

           rating
count  792.000000
mean     3.920455
std      1.154329
min      1.000000
25%      3.000000
50%      4.000000
75%      5.000000
max      5.000000

In [ ]:
BoardWay.info()

<class 'pandas.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   publishedDate  792 non-null    str
 1   title          792 non-null    str
 2   text           792 non-null    str
 3   rating         792 non-null    int64
dtypes: int64(1), str(3)
memory usage: 24.9 KB

In [30]:
BoardWay.isnull().sum().sum()#there was no null:))
BoardWay.duplicated().sum()

np.int64(0)

In [20]:
BoardWay["publishedDate"]=pd.to_datetime(BoardWay["publishedDate"])

In [21]:
BoardWay.head()

,publishedDate,title,text,rating
0,2024-01-07,Rude people with elder man,"Really rude people on the counter, they bully ...",1
1,2023-12-06,No te permiten entrar en el baño siendo cliente,"Una porquería de servicio , los camareros muy ...",1
2,2023-11-17,Pausa caffè,"Per me che sono un amante dell’espresso, il ca...",3
3,2023-10-06,cappuccino da passeggio,non potevo non provare anche lo Starbucks a Ne...,3
4,2023-09-04,Meglio il Chai del Matcha,In questa vacanza ho evitato questa catena (qu...,3

In [27]:
print(len(BoardWay))
print(len(BoardWay.columns))
#boardway.shape
print(BoardWay.columns)

792
4
Index(['publishedDate', 'title', 'text', 'rating'], dtype='str')

In [26]:
BoardWay.dtypes

publishedDate    datetime64[us]
title                       str
text                        str
rating                    int64
dtype: object

In [ ]:
BoardWay["rating"].max()
BoardWay["rating"].min()
BoardWay["rating"].mean().round(2)
BoardWay["rating"].median()
BoardWay["rating"].value_counts()[1]

np.float64(4.0)